name: Selenium Test

on:
  push:
    branches: [ "master" ]

jobs:
  TestOnLinux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Executing Selenium Test
      run: mvn clean test

  TestOnWindows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Executing Selenium Test
      run: mvn clean test
